# Generated by Django 3.1.3 on 2020-11-20 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 20, 0, 33, 945359)),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 20, 20, 0, 33, 945359)),
        ),
    ]
