# Generated by Django 3.1.3 on 2020-11-21 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201120_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 19, 50, 6, 83965)),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 19, 50, 6, 83965)),
        ),
    ]
