# Generated by Django 3.1.3 on 2020-11-21 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201121_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 19, 54, 4, 218638)),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 19, 54, 4, 218638)),
        ),
    ]
