# Generated by Django 3.1.3 on 2020-11-25 12:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201121_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='created_at',
            field=models.DateTimeField(auto_created=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
