# Generated by Django 3.1.3 on 2020-12-01 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20201201_2259'),
        ('choice', '0002_auto_20201201_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='question.closequestion'),
        ),
    ]
