# Generated by Django 3.1.3 on 2020-12-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number_of_choices',
            field=models.IntegerField(default=1),
        ),
    ]
