# Generated by Django 3.1.3 on 2020-12-01 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
        ('question', '0002_auto_20201201_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closequestion',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_questions', to='questionnaire.questionnaire'),
        ),
        migrations.AlterField(
            model_name='openquestion',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_questions', to='questionnaire.questionnaire'),
        ),
    ]
