# Generated by Django 3.1.3 on 2021-01-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respondents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openanswer',
            old_name='content',
            new_name='contents',
        ),
    ]
